version: '3.8'

services:
  currency-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
      - Jaeger__Host=jaeger
      - Jaeger__Port=6831
    depends_on:
      - seq
      - jaeger

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y

  jaeger:
    image: jaegertracing/all-in-one:1.50
    container_name: jaeger
    ports:
      - "16686:16686"
      - "6831:6831/udp"

